Flight crud made
XML-CETA/airline-backend pull request #9
Opened 2023-03-28 00:30 UTC by TerenjiD

2023-03-28 06:17 UTC, filipmilo requested changes

2023-03-28 06:17 UTC, filipmilo commented on main.go
> +	router.HandleFunc("/flights", flightHandler.GetOne).Methods("GET")
- We should have the flight id that we want to get in the request path such as 
```flights/{id}
```

2023-03-28 06:17 UTC, filipmilo commented on main.go
> +	router.HandleFunc("/flights", flightHandler.DeleteFlight).Methods("DELETE")
The same applies for delete

2023-03-31 09:01 UTC, Lee1312 approved these changes

2023-03-31 09:02 UTC, Lee1312 approved these changes

2023-03-31 09:25 UTC, filipmilo approved these changes

2023-03-31 09:25 UTC, merged